### ISSUE TITLE
Integrate Kismet with Graylog 

### ISSUE THREAD

**Issue by hithamsalama** [lennartkoopmann/nzyme#192]
Please I 'ld like to integrate Kismet with Graylog it would be a coperhensive intrusion detection solutuin.

1- In my system Nzyme, Kismet and Graylog are in the last version hosted on the same ubuntu.
It would be great if I could send alert messages from IDS Nzyme ans Kismet to Gralog.
I tried tio Input Jason HTML API from kismet but didn’work for me cause latest kismet API version reqire authentication to access the http jason path.

2- Please I have another question 
How can I integrate many nzyme sensors to one graylog.

please help me.

**Comment by lennartkoopmann** [comment]
Nzyme v1.0.0 will come with IDS functionality out of the box so this kind of integration is not on the roadmap.

Regarding the other question, you can just point as many nzyme instances as you wish to a single Graylog input.
