### ISSUE TITLE
Cann't find and connect to any wifi ssid

### ISSUE THREAD

**Issue by lasyka** [lennartkoopmann/nzyme#247]
My enveroment  is  linux on an android phone.
I compile form source, start nzyme succeful,  but the phone's wifi auto turn off.   Then i stop this proccess (ctrl+c)  . 
But  the phone  still can't list any wifi ssid, so cann't connect to wifi.
the only way is to restart the phone. 
How to fix it?

**Comment by lennartkoopmann** [comment]
Hi! Nzyme is not designed to run on Android.

I assume that you don't have a second WiFi adapter connected and what you see is your main WiFi adapter going into monitor mode, prohibiting it from connecting to access points.
