### ISSUE TITLE
Request for clarifications in README

### ISSUE THREAD

**Issue by ghoff** [lennartkoopmann/nzyme#34]
For those not familiar with Graylog, it would be helpful to have a brief description about creating a GELF input when discussing the graylog_addresses configuration option.  While not for the current version, this page helped me understand what I needed to do http://docs.graylog.org/en/2.1/pages/getting_started/config_input.html

The README does not show to run java with sudo. If I try to start it as documented on Ubuntu, nzyme fails to start when setting up the PCAP handle.  Do you recommend setting capabilities on the java executable so that sudo is not required?

When running on Ubuntu, I had to disable NetworkManager, or create an entry for my wireless network interface in /etc/network/interfaces which prevents NetworkManager from managing the device.   Otherwise NetworkManager would interfere with the device and prevent any frames from being captured.  Also, I had to make sure that the interface was up or the capture wouldn't start.

This is an amazing 0.1 release and your Derbycon presentation was fantastic.  Thank you for yet another contribution to the Open Source world.

**Comment by lennartkoopmann** [comment]
Thank you! I'll address this ASAP and moved it into the next milestone.

**Comment by lennartkoopmann** [comment]
rel #7

**Comment by lennartkoopmann** [comment]
All done. Thank you. :)

**Comment by ghoff** [comment]
Thank you!
