### ISSUE TITLE
which wifi card is supported?

### ISSUE THREAD

**Issue by y0d4a** [lennartkoopmann/nzyme#365]
Hi, i tried 4 different WIFI cards (which work in monitor mode when i test manual), and always getting:
```
21:52:01.557 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11Probe - Building PCAP handle on interface [wlan1mon]
21:52:01.578 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11Probe - Could not initialize probe [broad-monitor-wlan1mon]. Retrying soon.
```

**Comment by joramk** [comment]
I am using a RTL8188 USB dongle from Edimax for testing but I got lots of MalformedFrameException and I am not sure if the dongle is causing the error.
`Bus 001 Device 003: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]`

**Comment by y0d4a** [comment]
on which hw and OS did you installed?
i am starting to suspicious on arm.. i am trying it on raspberry 4 with kali installed on him..

**Comment by joramk** [comment]
> on which hw and OS did you installed?

Raspberry Pi OS on Raspberry Pi 4
`Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux`

**Comment by lennartkoopmann** [comment]
It looks like that card could work, but it requires a custom compilation of the driver. See also: https://forums.kali.org/showthread.php?37911-Getting-RTL8188-to-work-with-Kali-in-monitor-mode

I suggest using one of the officially tested WiFi adapters listed here: https://www.nzyme.org/documentation/requirements
