### ISSUE TITLE
ALFA AWUS036ACH

### ISSUE THREAD

**Issue by billford** [lennartkoopmann/nzyme#38]
Not really a bug or anything but the documentation uses the ALFA AWUS036ACH as one of its examples. I bought that one off of amazon and it doesn't seem to support monitor mode anymore (or I'm doing something horribly wrong, always possible). Just wanted to bring that up. Great project.

**Comment by markuta** [comment]
I remember a few weeks ago Kali released a new kernel update (4.12.6-1kali1) which completely broke wireless functionality with my card ALFA AWUS052NH. They have since updated and it works fine now. Not sure if this applies to your issue, as your card should be supported.
Maybe a driver issue?

**Comment by billford** [comment]
I'm running it on a raspberry pi so very very possible. Thanks for the reply.
