### ISSUE TITLE
Graylog webserver error

### ISSUE THREAD

**Issue by iAmG-r00t** [lennartkoopmann/nzyme#39]
so i setted up everything as you had described using a alfa AWUS036H wifi adapter my gray log is receiving messages from the gelf tcp input but when i veiw the messages it gives me this error : Loading field information failed with status: cannot get http://127.0.0.1:9000/api/system/fields (500) kindly help i am new to using graylog looked for solutions and i haven't find one could you kindly guide me on how you really configured your graylog webserver plus the lookup tables should i follow every single step from the documentation?

**Comment by lennartkoopmann** [comment]
This is an issue with Graylog and not nzyme. I recommend you ask your question in the [Graylog Community Forums](https://community.graylog.org).

Your `graylog-server` log file should indicate what errors you are running into and I suspect it is related to Elasticsearch.

**Comment by iAmG-r00t** [comment]
hi i am having an error while using a raspberry pi, i created a global tcp
gelf input assinged a bind address of 0.0.0.0 port 3030 and configured it
the same input on the nzyme config file but when i run nzyme it gives me
this error : 2:34:37.890 [gelfTcpTransport-1-1] ERROR
org.graylog2.gelfclient.transport.GelfTcpTransport - Connection failed:
Connection refused: /0.0.0.0:3030

 kindly help me on what to do..

**Comment by markuta** [comment]
I've written a quick guide on how to set up Nzyme and Graylog using Docker. Makes life a lot easier.
Link: https://markuta.com/how-to-set-up-nzyme-and-graylog/

Hope that helps you out.

**Comment by iAmG-r00t** [comment]
the set up i have already done but how did you allow nzyme from the respberry pi send data to the graylog  web server which is in another host machine

**Comment by iAmG-r00t** [comment]
or did you install graylog on the raspberry pi??
