### ISSUE TITLE
ALFA AWUS036ACH throws error when Nzyme starts. 

### ISSUE THREAD

**Issue by prasket** [lennartkoopmann/nzyme#42]
When trying to use the ALFA AWUS036ACH on a Raspberry Pi 3 B with Nzyme I am getting errors. 
I am opening an issue because README states that this device has been proven with Nzyme. 

The RaspberryPI did not recognize the AWUS036ACH on initial plugin of so I found a post on raspberrypi forums where someone had a made a wifi driver tool found here: https://www.raspberrypi.org/forums/viewtopic.php?p=1210087#p1210087 

Here is the error that was generated by Nzyme:

> 13:50:49.030 [main] INFO  horse.wtf.nzyme.Nzyme - Building PCAP handle on interface [wlx00c0ca964d63]
13:50:49.075 [main] ERROR horse.wtf.nzyme.Main - Boot error.
horse.wtf.nzyme.NzymeInitializationException: Could not build PCAP handle.
	at horse.wtf.nzyme.NzymeImpl.<init>(NzymeImpl.java:128) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.Main.main(Main.java:100) [nzyme-0.2-SNAPSHOT.jar:?]
Caused by: org.pcap4j.core.PcapNativeException: wlx00c0ca964d63: SIOCGIWPRIV: Argument list too long
	at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:47) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1671) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.NzymeImpl.<init>(NzymeImpl.java:122) ~[nzyme-0.2-SNAPSHOT.jar:?]
	... 1 more
13:50:49.091 [shutdown-hook] INFO  horse.wtf.nzyme.Main - Shutting down.

I have Nzyme successfully running with a ALFA AWUS036NH (also listed in README) but this device is only 2.4 ghz (README states that it is 2.4/5ghz that is wrong) and I want to include 5ghz which is why the ALFA AWUS036ACH.

**Comment by lennartkoopmann** [comment]
Hi, what Linux distribution and version are you running on the Pi? Last time I checked, that specific adapter worked out of the box on a Raspbian Stretch. Happy to try it again if you are on that, or a newer version.

**Comment by malled** [comment]
Hello, I've just used both AWUS036ACH and AWUS036NH successfully on kali with nzyme. But on a laptop and not a raspberry.

If the adapter does not work at all, it may be a driver issue. You could try another distribution and see if it works for you.

You may check if it works with

 `airmon-ng start wlan0`,

maybe with a 

```
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode monitor
sudo ifconfig wlan0 up
```

and 

`airmon-ng check kill`

before.

**Comment by sirkus9** [comment]
I can confirm this same problem with a new (as of July 10, 2018)  installation of raspbian stretch, and an AWUS036ACH. After installing the driver (as original post mentions), I can start it up and even get it into monitor mode, but it won't work with nzyme. I get the same error as noted by the prasket. (argument list too long.)

**Comment by prasket** [comment]
woah sorry I missed the question @lennartkoopmann 
The image I installed on the Raspberry Pi 3 was "2018-04-18-raspbian-stretch.img" downloaded from https://www.raspberrypi.org/downloads/raspbian/ 

Looks like @sirkus9 has also ran into this. I am happy to give it a try again this weekend. 

Here is the latest distro info from Raspbian site: 

> Image with desktop based on Debian Stretch
> Version: June 2018
> Release date: 2018-06-27
> Kernel version: 4.14

**Comment by sirkus9** [comment]
Okay, here's an update about what's working on my end, in case it helps anyone. 

I installed a fresh image of 2018-06-27-raspbian-stretch-lite.img onto a Raspberry Pi. With this fresh install, the ALFA AUS036ACH didn't have drivers that worked. If you search for rtl8812au drivers, lots of versions come up. I tried several. In the end, what worked is the aircrack-ng/rtl8812au (https://github.com/aircrack-ng/rtl8812au) driver Note that the DKMS installation instructions did not work out of the box for me. I ended up using the direct "make/make install" method described in the aircrack-ng/rtl8812au instructions.

The short story is this worked for nzyme. I get no errors, and its capturing on 2.4G and 5G channels.

**Comment by prasket** [comment]
Thank you for the info @sirkus9 | I will try to make some time soon to try out those same steps and driver repo.

**Comment by lennartkoopmann** [comment]
The `aircrack-ng/rtl8812au` driver works for me, too. I've updated this in the README here: 430bc7b54e48575afdb6c6b740e518c6330b3ab4

Thanks everyone!

**Comment by nitram2342** [comment]
I have AUS036ACH cards, too. When I installed the second card, I run into this issue again. Therefore, I like to summarize what is necessary to get it running.

- Use the `aircrack-ng/rtl8812au` driver.
- Use the lines below to enable monitor mode. Adjust the WiFi device if necessary.
```
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode monitor
sudo ifconfig wlan0 up

```
- Use `skip_enable_monitor: true` in the `nzyme.conf`. Otherwise you get the error message too, even if the monitor mode is already enabled.
