### ISSUE TITLE
Signal strength appears very weak

### ISSUE THREAD

**Issue by mathieubrun** [lennartkoopmann/nzyme#459]
Version : 1.2.0-SNAPSHOT

The signal strengths of nearly all the networks appeared to be very weak:
![image](https://user-images.githubusercontent.com/408847/119263232-767d7780-bbde-11eb-952e-883b74591773.png)

I did try using bettercap, and the results where very different:
![image](https://user-images.githubusercontent.com/408847/119262932-4386b400-bbdd-11eb-85ea-1c29798cb983.png)

After investigating with wireshark there are 2 fields in radiotap header containing signal strength:
![image](https://user-images.githubusercontent.com/408847/119263595-f821d500-bbdf-11eb-933a-291d7401944f.png)

I did a quick patch to use the first one (so antennaSignal is not overwritten) in https://github.com/lennartkoopmann/nzyme/blob/master/src/main/java/horse/wtf/nzyme/dot11/Dot11MetaInformation.java#L88

After the patch, the strengths are more realistic:
![image](https://user-images.githubusercontent.com/408847/119263079-e3444200-bbdd-11eb-8f28-06c6e98cebb8.png)

And also not "all over the place" in the waterfall diagram:

(new version deployed at 23:00)
![image](https://user-images.githubusercontent.com/408847/119262684-5d73c700-bbdc-11eb-9fea-c327c325dc4c.png)

I can do a PR if it helps

PS : awesome tool !

**Comment by lennartkoopmann** [comment]
Thank you. I'm investigating.

**Comment by lennartkoopmann** [comment]
Thanks for spotting this and the clear report. I was not able to reproduce this (I only have one antenna signal field) but I assume it might be related to WiFi adapters with multiple antennas or simply a faulty driver. What WiFi adapter do you use? Does it have multiple antennas? What OS are you on?

I'm still writing a patch to only read the first antenna signal field.

**Comment by lennartkoopmann** [comment]
Patch backported to `v1.1`

**Comment by mathieubrun** [comment]
OS : Linux 5.12.12-arch1-1
Driver : https://github.com/aircrack-ng/rtl8812au
Adapter : https://eu.dlink.com/uk/en/products/dwa-172-wireless-ac600-dual-band-high-gain-usb-adapter

**Comment by lennartkoopmann** [comment]
I was not able to reproduce this in any of my adapters but will keep an eye on it in the future. The patch should fix the wrong behavior.

Thanks again for the great report! Please re-open if v1.1.1 does not resolve this for you.
