### ISSUE TITLE
rt8812au 5G wireless network card does not support, unable to start

### ISSUE THREAD

**Issue by LuckyFishGeek** [lennartkoopmann/nzyme#504]
airmon-ng check kill
ip link set wlan0 down
iw dev wlan0 set type monitor
ip link set wlan0 up
![Snipaste_2021-08-23_08-57-28](https://user-images.githubusercontent.com/29472751/130376607-8e2207d4-5461-4458-9370-12a33263bcb4.png)
![Snipaste_2021-08-23_08-57-45](https://user-images.githubusercontent.com/29472751/130376610-b37f954f-402b-437b-bcfa-c82aab63a1c6.png)
![Snipaste_2021-08-23_08-58-03](https://user-images.githubusercontent.com/29472751/130376611-c34f2df6-521d-49e4-b452-34410b821f1c.png)
![Snipaste_2021-08-23_08-58-55](https://user-images.githubusercontent.com/29472751/130376612-80343573-3abf-49ea-b4bd-9d2800bcfb3e.png)

**Comment by lennartkoopmann** [comment]
What does your `nzyme.log` file show?

**Comment by LuckyFishGeek** [comment]
> What does your `nzyme.log` file show?
Thank you for your answer, I will upload the log tomorrow.
