### ISSUE TITLE
Support for other Logging providers

### ISSUE THREAD

**Issue by jouellnyc** [lennartkoopmann/nzyme#51]
It would be great to be able to point to http://logz.io whether via rsyslog, logstash or other "out of the box".

**Comment by lennartkoopmann** [comment]
I'll be very upfront here and please don't take it the wrong way. Given my involvement with Graylog, I won't be spending time on this.

However, you can certainly send messages from nzyme into a [Logstash GELF input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-gelf.html) and route it wherever you want from there.

Thank you very much and I hope you understand. :)
