### ISSUE TITLE
Trap PROBE_REQUEST_1 cannot write to STDERR

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [lennartkoopmann/nzyme#517]
Dear cummunity, hi lennart,

with version 1.1.0 I'm getting this error when I try to setup a trap:

10:35:41.932 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Started web interface and REST API at [http://10.10.1.33:22900/]. Access it at: [http://10.10.1.33:22900/]
10:35:41.955 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlan1] ... (⌐■_■)–︻╦╤─ – – pew pew
10:35:42.023 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Registering frame interceptors of [horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap].
10:35:43.370 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan1]
10:35:44.426 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - PCAP handle for [broad-monitor-wlan1] acquired. Cycling through channels <1,2,3,4,5,6,7,8,9,10,11>.
10:35:47.034 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.probes.Dot11SenderProbe - PCAP handle for [trap-sender-wlan2-PROBE_REQUEST_1] acquired. Cycling through channels <11>.
10:35:51.279 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: Invoked command {/usr/bin/python3.7 /tmp/nzyme_ProbeRequest --interface wlan2 --ssid tmobile --mac B4:8B:19:A6:54:D9}.
10:35:51.280 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: 6 lines written to STDERR:
10:35:51.281 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Could not connect: Connection refused
10:35:51.282 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Verbindung ist gescheitert: Connection refused
10:35:51.283 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
10:35:51.284 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:6806): Gdk-CRITICAL **: 10:35:49.433: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
10:35:51.285 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
10:35:51.286 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:6806): Gdk-CRITICAL **: 10:35:49.439: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
10:35:51.288 [probe-loop-1] ERROR horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap - Could not set ProbeRequestTrap for SSID [tmobile].
horse.wtf.nzyme.dot11.deception.bluffs.Bluff$BluffExecutionException: STDERR is not empty.
	at horse.wtf.nzyme.dot11.deception.bluffs.Bluff.execute(Bluff.java:99) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap.doRun(ProbeRequestTrap.java:84) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.Trap.run(Trap.java:75) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11SenderProbe.lambda$loop$0(Dot11SenderProbe.java:118) ~[nzyme-1.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

Any hints?
Regards

JD.

**Comment by lennartkoopmann** [comment]
Can you try to run the following command and post the full output?

```
/usr/bin/python3.7 /tmp/nzyme_ProbeRequest --interface wlan2 --ssid tmobile --mac B4:8B:19:A6:54:D9
```

**Comment by JohnDoeIsKIng** [comment]
Hi Lennart,

sure:

`pi@raspberrypi:~ $ /usr/bin/python3.7 /tmp/nzyme_ProbeRequest --interface wlan2 --ssid tmobile --mac B4:8B:19:A6:54:D9
/usr/bin/python3.7: can't open file '/tmp/nzyme_ProbeRequest': [Errno 2] No such file or directory
`

Thanx in advance.
Regards

JD.

**Comment by lennartkoopmann** [comment]
The German error messasges make this a little confusing to compare but can you please try this? https://www.nzyme.org/docs/knowledge-base/common-permission-problems#trap-execution-operation-not-permitted

**Comment by JohnDoeIsKIng** [comment]
Hi Lennart,

that 's it! On the Pi there was a /usr/bin/python3.7 instead of /usr/bin/python3.8.
Many thanx!
Best regards

JD.

**Comment by JohnDoeIsKIng** [comment]
Solved by

https://www.nzyme.org/docs/knowledge-base/common-permission-problems#trap-execution-operation-not-permitted

**Comment by JohnDoeIsKIng** [comment]
Oh no, that was a little bit quick:
`13:53:06.261 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: Invoked command {/usr/bin/python3.7 /tmp/nzyme_ProbeRequest --interface wlan2 --ssid tmobile --mac B4:8B:19:A6:54:D9}.
13:53:06.261 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: 6 lines written to STDERR:
13:53:06.262 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Could not connect: Connection refused
13:53:06.262 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Verbindung ist gescheitert: Connection refused
13:53:06.262 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
13:53:06.262 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:30839): Gdk-CRITICAL **: 13:53:04.504: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
13:53:06.263 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
13:53:06.263 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:30839): Gdk-CRITICAL **: 13:53:04.509: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
13:53:06.263 [probe-loop-1] ERROR horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap - Could not set ProbeRequestTrap for SSID [tmobile].
horse.wtf.nzyme.dot11.deception.bluffs.Bluff$BluffExecutionException: STDERR is not empty.
	at horse.wtf.nzyme.dot11.deception.bluffs.Bluff.execute(Bluff.java:99) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap.doRun(ProbeRequestTrap.java:84) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.Trap.run(Trap.java:75) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11SenderProbe.lambda$loop$0(Dot11SenderProbe.java:118) ~[nzyme-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`
Before:
`pi@raspberrypi:~ $ sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/python3.7
pi@raspberrypi:~ $ 
`

**Comment by JohnDoeIsKIng** [comment]
I've managed to narrow the source of the error down do the import of scapy:

`pi@raspberrypi:~ $ python3.7
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
Unable to init server: Could not connect: Connection refused
Unable to init server: Verbindung ist gescheitert: Connection refused

(.:13749): Gdk-CRITICAL **: 13:32:39.676: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(.:13749): Gdk-CRITICAL **: 13:32:39.682: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
>>> 
`
This seems to be a documented import error, but I'm not sure how to solve it.

**Comment by JohnDoeIsKIng** [comment]
Dear community,
dear Lennart,

with a snapshot of the current source the TRAP-error is still pending:
`12:00:18.999 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: Invoked command {/usr/bin/python3.7 /tmp/nzyme_ProbeRequest --interface wlan2 --ssid tmobile --mac B4:8B:19:A6:54:D9}.
12:00:19.000 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.ProbeRequest]: 6 lines written to STDERR:
12:00:19.001 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Could not connect: Connection refused
12:00:19.003 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: Unable to init server: Verbindung ist gescheitert: Connection refused
12:00:19.003 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
12:00:19.004 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:31097): Gdk-CRITICAL **: 12:00:16.980: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
12:00:19.005 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: 
12:00:19.006 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - 		STDERR: (nzyme_ProbeRequest:31097): Gdk-CRITICAL **: 12:00:16.984: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
12:00:19.007 [probe-loop-1] ERROR horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap - Could not set ProbeRequestTrap for SSID [tmobile].
horse.wtf.nzyme.dot11.deception.bluffs.Bluff$BluffExecutionException: STDERR is not empty.
	at horse.wtf.nzyme.dot11.deception.bluffs.Bluff.execute(Bluff.java:99) ~[nzyme-1.2.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.ProbeRequestTrap.doRun(ProbeRequestTrap.java:84) ~[nzyme-1.2.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.deception.traps.Trap.run(Trap.java:75) ~[nzyme-1.2.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11SenderProbe.lambda$loop$0(Dot11SenderProbe.java:118) ~[nzyme-1.2.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`
Before I've tried the setcap:

`pi@raspberrypi:~ $ sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/python3.7
`

Any hints to solve this are appreciated !
Regards

JD.

**Comment by JohnDoeIsKIng** [comment]
Dear all,

I've managed to get the TRAP running:
It's proven a python issue (2.7 vs. 3.7 or 3.8).
If the python path (in /etc/nzyme/nzyme.conf) is /usr/bin/python3.7 or /usr/bin/python3.8 the above mentioned error comes up.
If the python path is /usr/bin/python2.7 everything runs fine.
Best regards

JD.
