### ISSUE TITLE
MT7612U 5G wireless network card does not support, unable to start

### ISSUE THREAD

**Issue by LuckyFishGeek** [lennartkoopmann/nzyme#531]
airmon-ng check kill
ip link set wlan0 down
iw dev wlan0 set type monitor
ip link set wlan0 u

nzyme logs:

[nzyme.log](https://github.com/lennartkoopmann/nzyme/files/7189153/nzyme.log)

![Snipaste_2021-09-18_11-17-13](https://user-images.githubusercontent.com/29472751/133870758-72c69f41-f5b3-4c54-b543-feec7eee0a32.png)
p
![Snipaste_2021-09-18_11-17-59](https://user-images.githubusercontent.com/29472751/133870769-cb5c1671-d04b-4a92-b885-c780b7f46969.png)
![Snipaste_2021-09-18_11-18-43](https://user-images.githubusercontent.com/29472751/133870795-d7fedc93-8274-4206-9774-4c53ef0730e5.png)
![Snipaste_2021-09-18_11-55-52](https://user-images.githubusercontent.com/29472751/133871751-aac6257a-7579-4b51-944d-dc24a524ce34.png)

**Comment by lennartkoopmann** [comment]
Please try using `skip_enable_monitor`: https://www.nzyme.org/docs/installation-configuration/configuration-reference#802_11_monitorsskip_enable_monitor

**Comment by LuckyFishGeek** [comment]
> Please try using `skip_enable_monitor`: https://www.nzyme.org/docs/installation-configuration/configuration-reference#802_11_monitorsskip_enable_monitor

Thank you for your help, I will try it and give feedback

**Comment by MoHorst** [comment]
@LuckyFishGeek 
did you fixed the path to python?

11:06:25.790 [main] ERROR horse.wtf.nzyme.Main - Invalid configuration. Please refer to the example configuration file or documentation.
horse.wtf.nzyme.configuration.InvalidConfigurationException: Parameter [general.python.path] does not point to an executable file: /usr/bin/python3.8

**Comment by LuckyFishGeek** [comment]
> @LuckyFishGeek
> did you fixed the path to python?
> 
> 11:06:25.790 [main] ERROR horse.wtf.nzyme.Main - Invalid configuration. Please refer to the example configuration file or documentation.
> horse.wtf.nzyme.configuration.InvalidConfigurationException: Parameter [general.python.path] does not point to an executable file: /usr/bin/python3.8

I'm experiencing the same error and I don't know how to fix it yet.

**Comment by lennartkoopmann** [comment]
You have to install Python and tell nzyme where the Python executable can be found. On Linux, you can find the path using `which python`.
