### ISSUE TITLE
nzyme.conf file permissions

### ISSUE THREAD

**Issue by nitram2342** [lennartkoopmann/nzyme#555]
In step 5 of the documentation, a sample config file is copied to the conf directory, but file permissions are not adjusted afterwards, despite the conf file has db credentials and an admin password hash. Maybe it could be adjusted to a chmod 640 nzyme.conf; chown root.root nzyme.conf.

**Comment by lennartkoopmann** [comment]
Thank you! Including in v2.0.0 backlog.

**Comment by lennartkoopmann** [comment]
Done in 503afc3b. The DEB package is automatically creating the `.conf` file now, with 640 permissions. Thank you!
