### ISSUE TITLE
BEACON_1 and PROBE_REQUEST_1 traps do not work

### ISSUE THREAD

**Issue by nitram2342** [lennartkoopmann/nzyme#556]
I am testing nzyme. Thank you very much for the cool tool. I tried to use the BEACON_1 and the PROBE_REQUEST_1 trap. Simply spoken, BEACON_1 should emulate a Wifi network and PROBE_REQUEST_1 will check, if there is a response to probe requests. I can't see any advertised network for the BEACON_1 trap and if I set up a WiFi network that is listed in the  PROBE_REQUEST_1 `ssids` list, it does not raise an alarm. According to the dashboard, everything is up an running. How can I debug this?

**Comment by nitram2342** [comment]
I traced the issue a bit. I used a test installation on a Raspberry Pi, which isn't the fasted device. In case of the BEACON_1 probe, a script is launched in a loop. When I run the script manually, the script runs for nearly 4 seconds. I think loading all the scapy modules takes a while. This is why the SSID does not show up. Sometimes it does, but usually not.

```
$ time /usr/bin/python3 /tmp/nzyme_Beacon --interface wlx00XXXXXXXXXX --ssid XXXXX --mac XX:XX:XX:XX:XX:XX 

real	0m3,971s
user	0m3,523s
sys	0m0,319s

```

When I change the python code to run `beacon()` in a loop (while nzym is stopped), it is fine and the SSID becomes observable in the list of WiFis.

Regarding other script, I noticed a bug. I have multiple SSIDs in the PROBE_REQUEST_1 list similar to what is written in the documentation. When I observe running processes, I only see the first SSID being used as parameter, but not the other SSIDs from the nzym.conf file.

**Comment by Quas7** [comment]
I have a similar behavior on a Celeron-based setup. SSID shows up only sporadically and CPU usage is ~90% on both cores.
Setup is reported as working as well.
`00:12:55.536 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.probes.Dot11SenderProbe - PCAP handle for [trap-sender-wlxdc4ef40a3eaa-BEACON_1] acquired. Cycling through channels <1,11>.`

But could also be related to getting hammered with these malformed frames as the noise floor is quite high in my area with 100+ wifi networks. I also see unlimited fingerprints for my own networks and random SSIDs gathering.
`00:06:13.464 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff f0 b0 14 ba 2d a0 f0 b0 14 ba 2d a0 d0 8a 80 41 0a 48 63 00 00 00 64 00 31 14 00 05 57 6f 74 61 6e 01 08 82 84 8b 96 8c 12 98 24 03 01 01 05 04 00 01 00 00 07 06 44 45 20 01 0d 14 2a 01 02 32 04 b0 48 60 6c 0b 05 02 00 47 00 00 46 05 73 d0 00 00 0c 2d 1a ad 01 1b ff ff 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 04 06 e6 a7 0c 00 3d 16 01 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 08 05 00 0f 00 00 00 00 40 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 dd 09 00 03 7f 01 01 00 00 ff 7f dd 08 8c fd f0 01 01 02 01 00 dd 16 8c fd f0 04 00 00 49 00 00 03 02 09 72 01 00 00 00 00 3d 00 00 00 dd 0c 00 04 0e 01 01 02 01 00 00 00 00 00 dd 1d 00 50 f2 04 10 4a 00 01 10 10 44 00 01 02 10 3c 00 01 01 10 49 00 06 00 37 2a 00 01 20 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 42 39 d0 34`

**Comment by lennartkoopmann** [comment]
The new nzyme v2.0 architecture will do this entirely different and this should no longer be an issue going forward. Thank you!
