### ISSUE TITLE
Favicon not showing in Chrome-based browsers

### ISSUE THREAD

**Issue by Katharsis13** [lennartkoopmann/nzyme#569]
Hi, im having a minor problem with the favicon which is not shown correctly in Chrome-based browsers. If the location of favicon is browsed directly, only a white plane is shown. It works perfectly in Firefox though. If the size of the favicon ist changed to a square format like 256x256 Chrome and co are able to display it. Can anyone confirm this problem? (How) can I change the favicon inside the jar? Or will there be a fix in the next release? Thanks a lot.

**Comment by lennartkoopmann** [comment]
Thank you very much for reporting this and including the additional information. Fixed in 53ab7202b3f251cec2294eaae7cb64c641fcb2a6 and will be included in v1.2.0.
