### ISSUE TITLE
Malformed 802.11 tagged parameters

### ISSUE THREAD

**Issue by void4main** [lennartkoopmann/nzyme#638]
Hi,

I have a lot of messages like this:
**INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff [...]**

And it looks like only these (broadcast (?)) packages are 'malformed' and therefore not processed.
But from a wireshark perspective these look perfectly fine.

I guess the result is that my 'networks' list in nzyme is very short ~5 entries at a time but I would expect more then 20.
Does nzyme process broadcast packages? Bug or feature? :)

Thank you!

**Setup:**
nzyme: 1.2.2 built at [2021-12-10T15:28:11Z].
Raspberry Pi4
Linux echo01 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
Alfa Awus1900
rtl8814au aircrack-ng/rtl8814au.git

**Comment by lennartkoopmann** [comment]
Can you post your nzyme log file as well as a PCAP of a few minutes of WiFi traffic? Feel free to email it to me if you don't want to post it publicly.

**Comment by void4main** [comment]
Thank you, the email is on its way ...

**Comment by lennartkoopmann** [comment]
Can you post the full log file, including the entire line that includes the payload? One line should say "Malformed 802.11 tagged parameters." and the other one will include "Could not parse 802.11 tagged parameters.". Please include the full stack trace.
