### ISSUE TITLE
Unexpected UNEXPECTED_SSID_PROBERESP && UNEXPECTED_FINGERPRINT_BEACONs

### ISSUE THREAD

**Issue by void4main** [lennartkoopmann/nzyme#639]
Hi,

I have UNEXPECTED_FINGERPRINT_BEACONs && UNEXPECTED_SSID_PROBERESP alerts eventough the devices, fingerprints etc. listed correctly in the Assets list.

I use a slash (/) and spaces in both of my populated ESSIDs.
2.4 and 5 GHz with these channels are used: [1,2,3,4,5,6,7,8,9,10,11,12,13,36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128]

**Setup:**
nzyme: 1.2.2 built at [2021-12-10T15:28:11Z].
Raspberry Pi4
Linux echo01 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
Alfa Awus1900
rtl8814au aircrack-ng/rtl8814au.git

**Comment by lennartkoopmann** [comment]
Can you post your nzyme configuration file and a copy of the alert details?

**Comment by void4main** [comment]
Thank you, email is on its way ...

**Comment by lennartkoopmann** [comment]
This will be solved with the new architecture in v2.0.
