### ISSUE TITLE
Error in nzyme.log

### ISSUE THREAD

**Issue by Calimerorulez** [lennartkoopmann/nzyme#666]
Hi,

I'm seeing lines like this in nzyme.log 5 times per second:

`15:46:30.870 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 78 45 58 69 04 85 78 45 58 69 04 85 b0 95 9a f1 0f 68 88 00 00 00 64 00 11 04 00 07 4d 65 74 65 6f 72 61 01 08 82 84 8b 96 12 24 48 6c 03 01 01 32 04 0c 18 30 60 05 04 00 01 00 ee 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 04 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 01 00 1d 12 7a dd 07 00 0c 43 03 00 00 00 dd 13 00 15 ed 00 01 01 00 01 02 12 a6 81 06 78 45 58 69 04 84 74 1b cb 39`

What could I do to resolve this?

**Comment by lennartkoopmann** [comment]
Can you post the complete log? It should include a message like "Could not parse 802.11 tagged parameters", too.
