### ISSUE TITLE
insufficient enconding of control characters in urls?

### ISSUE THREAD

**Issue by jweglinski** [lennartkoopmann/nzyme#670]
Hello!
Nzyme version 1.2.2.
After discovering SSID of '[' I cannot enter links (ssid, bssid) on alert page. When I try I get a following exception in GUI:

Internal Server Error
java.net.URISyntaxException: Illegal character in path at index 63: http://NZYME_IP:22900/networks/show/MAC_ADDR_HERE/%01[/11

     1: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:463)
     2: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:339)
     3: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
     4: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
     5: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
     6: java.base/java.lang.Thread.run(Thread.java:829)

Root Cause: java.net.URISyntaxException: Illegal character in path at index 63: http://NZYME_IP:22900/networks/show/MAC_ADDR_HERE/%01[/11

     1: java.base/java.net.URI$Parser.fail(URI.java:2913)
     2: java.base/java.net.URI$Parser.checkChars(URI.java:3084)
     3: java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
     4: java.base/java.net.URI$Parser.parse(URI.java:3114)
     5: java.base/java.net.URI.(URI.java:600)
     6: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:461)
     7: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:339)
     8: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
     9: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
    10: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)

**Comment by lennartkoopmann** [comment]
This should be working in v1.3.0, which comes with a pretty deep web interface rewrite. When confirming this, I noticed that the networks page did still not work with some special characters in a SSID and I'm using this issue to track the fix.

**Comment by lennartkoopmann** [comment]
Confirmed to be working now in v1.3.0 (not yet released). Tested with the SSIDs:

![Screenshot 2022-03-19 113549](https://user-images.githubusercontent.com/35022/159129979-9447e146-3770-4c80-adea-30eb17944dc9.jpg)
