### ISSUE TITLE
Armbian: Nzyme does not start

### ISSUE THREAD

**Issue by Mierscheid** [lennartkoopmann/nzyme#681]
Armbian Bullseye with kernel 5.10.68-station (Balbes image) on an T95 max TV box (Allwinner H6, 2 GB RAM, 16 GB eNVMe).
I followed the instructions for Raspian. 
The only thing is that I only get wlan0 instead of a Predictable Interface Name.

After starting, Nzyme seems to restart again and again without success.
The log only says:

11:45:54.432 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [email].
11:45:54.443 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [file].

How can I increase the log level to Verbose? There seems to be only "WARN" and "ERROR"?

TIA
Regards
Mierscheid

**Comment by lennartkoopmann** [comment]
Nzyme would log anything that went wrong as an error. I recommend checking `journalctl -xe` to see if something outside of the nzyme process caused it to crash or shut down.
