### ISSUE TITLE
Still in maintenance?

### ISSUE THREAD

**Issue by Mierscheid** [lennartkoopmann/nzyme#684]
Is the project still in maintenance? It does not look like it. 
Can anyone recommend me an alternative?

TIA
Mierscheid

**Comment by lennartkoopmann** [comment]
It very much is, but you might be better served looking for alternatives after leaving a long message about how terrible software developers are and how bad this project is in another post. No one owes you software free of cost and I'm sure you can find something that solves your needs somewhere else! ✌️ 

The [Code of Conduct](https://github.com/lennartkoopmann/nzyme/blob/master/CODE_OF_CONDUCT.md) holds more details.
